# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/dnurr/Scrivania/clion-2024.2.1/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /home/dnurr/Scrivania/clion-2024.2.1/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/dnurr/My Passport/Progetti/Dev/Engine/New/CMEngine (Linux)/CMEngine"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/dnurr/My Passport/Progetti/Dev/Engine/New/CMEngine (Linux)/CMEngine"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/dnurr/Scrivania/clion-2024.2.1/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/dnurr/Scrivania/clion-2024.2.1/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/dnurr/My Passport/Progetti/Dev/Engine/New/CMEngine (Linux)/CMEngine/CMakeFiles" "/media/dnurr/My Passport/Progetti/Dev/Engine/New/CMEngine (Linux)/CMEngine//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/dnurr/My Passport/Progetti/Dev/Engine/New/CMEngine (Linux)/CMEngine/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CMEngine

# Build rule for target.
CMEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CMEngine
.PHONY : CMEngine

# fast build rule for target.
CMEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/build
.PHONY : CMEngine/fast

#=============================================================================
# Target rules for targets named CMEngine_autogen_timestamp_deps

# Build rule for target.
CMEngine_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CMEngine_autogen_timestamp_deps
.PHONY : CMEngine_autogen_timestamp_deps

# fast build rule for target.
CMEngine_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine_autogen_timestamp_deps.dir/build.make CMakeFiles/CMEngine_autogen_timestamp_deps.dir/build
.PHONY : CMEngine_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named CMEngine_autogen

# Build rule for target.
CMEngine_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CMEngine_autogen
.PHONY : CMEngine_autogen

# fast build rule for target.
CMEngine_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine_autogen.dir/build.make CMakeFiles/CMEngine_autogen.dir/build
.PHONY : CMEngine_autogen/fast

CMEngine_autogen/mocs_compilation.o: CMEngine_autogen/mocs_compilation.cpp.o
.PHONY : CMEngine_autogen/mocs_compilation.o

# target to build an object file
CMEngine_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/CMEngine_autogen/mocs_compilation.cpp.o
.PHONY : CMEngine_autogen/mocs_compilation.cpp.o

CMEngine_autogen/mocs_compilation.i: CMEngine_autogen/mocs_compilation.cpp.i
.PHONY : CMEngine_autogen/mocs_compilation.i

# target to preprocess a source file
CMEngine_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/CMEngine_autogen/mocs_compilation.cpp.i
.PHONY : CMEngine_autogen/mocs_compilation.cpp.i

CMEngine_autogen/mocs_compilation.s: CMEngine_autogen/mocs_compilation.cpp.s
.PHONY : CMEngine_autogen/mocs_compilation.s

# target to generate assembly for a file
CMEngine_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/CMEngine_autogen/mocs_compilation.cpp.s
.PHONY : CMEngine_autogen/mocs_compilation.cpp.s

Engine/GUI/guibuilder.o: Engine/GUI/guibuilder.cpp.o
.PHONY : Engine/GUI/guibuilder.o

# target to build an object file
Engine/GUI/guibuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/GUI/guibuilder.cpp.o
.PHONY : Engine/GUI/guibuilder.cpp.o

Engine/GUI/guibuilder.i: Engine/GUI/guibuilder.cpp.i
.PHONY : Engine/GUI/guibuilder.i

# target to preprocess a source file
Engine/GUI/guibuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/GUI/guibuilder.cpp.i
.PHONY : Engine/GUI/guibuilder.cpp.i

Engine/GUI/guibuilder.s: Engine/GUI/guibuilder.cpp.s
.PHONY : Engine/GUI/guibuilder.s

# target to generate assembly for a file
Engine/GUI/guibuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/GUI/guibuilder.cpp.s
.PHONY : Engine/GUI/guibuilder.cpp.s

Engine/Panels/panel.o: Engine/Panels/panel.cpp.o
.PHONY : Engine/Panels/panel.o

# target to build an object file
Engine/Panels/panel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Panels/panel.cpp.o
.PHONY : Engine/Panels/panel.cpp.o

Engine/Panels/panel.i: Engine/Panels/panel.cpp.i
.PHONY : Engine/Panels/panel.i

# target to preprocess a source file
Engine/Panels/panel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Panels/panel.cpp.i
.PHONY : Engine/Panels/panel.cpp.i

Engine/Panels/panel.s: Engine/Panels/panel.cpp.s
.PHONY : Engine/Panels/panel.s

# target to generate assembly for a file
Engine/Panels/panel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Panels/panel.cpp.s
.PHONY : Engine/Panels/panel.cpp.s

Engine/Panels/properties.o: Engine/Panels/properties.cpp.o
.PHONY : Engine/Panels/properties.o

# target to build an object file
Engine/Panels/properties.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Panels/properties.cpp.o
.PHONY : Engine/Panels/properties.cpp.o

Engine/Panels/properties.i: Engine/Panels/properties.cpp.i
.PHONY : Engine/Panels/properties.i

# target to preprocess a source file
Engine/Panels/properties.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Panels/properties.cpp.i
.PHONY : Engine/Panels/properties.cpp.i

Engine/Panels/properties.s: Engine/Panels/properties.cpp.s
.PHONY : Engine/Panels/properties.s

# target to generate assembly for a file
Engine/Panels/properties.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Panels/properties.cpp.s
.PHONY : Engine/Panels/properties.cpp.s

Engine/Rendering/renderer.o: Engine/Rendering/renderer.cpp.o
.PHONY : Engine/Rendering/renderer.o

# target to build an object file
Engine/Rendering/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Rendering/renderer.cpp.o
.PHONY : Engine/Rendering/renderer.cpp.o

Engine/Rendering/renderer.i: Engine/Rendering/renderer.cpp.i
.PHONY : Engine/Rendering/renderer.i

# target to preprocess a source file
Engine/Rendering/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Rendering/renderer.cpp.i
.PHONY : Engine/Rendering/renderer.cpp.i

Engine/Rendering/renderer.s: Engine/Rendering/renderer.cpp.s
.PHONY : Engine/Rendering/renderer.s

# target to generate assembly for a file
Engine/Rendering/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Rendering/renderer.cpp.s
.PHONY : Engine/Rendering/renderer.cpp.s

Engine/Windows/mainwindow.o: Engine/Windows/mainwindow.cpp.o
.PHONY : Engine/Windows/mainwindow.o

# target to build an object file
Engine/Windows/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Windows/mainwindow.cpp.o
.PHONY : Engine/Windows/mainwindow.cpp.o

Engine/Windows/mainwindow.i: Engine/Windows/mainwindow.cpp.i
.PHONY : Engine/Windows/mainwindow.i

# target to preprocess a source file
Engine/Windows/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Windows/mainwindow.cpp.i
.PHONY : Engine/Windows/mainwindow.cpp.i

Engine/Windows/mainwindow.s: Engine/Windows/mainwindow.cpp.s
.PHONY : Engine/Windows/mainwindow.s

# target to generate assembly for a file
Engine/Windows/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/Engine/Windows/mainwindow.cpp.s
.PHONY : Engine/Windows/mainwindow.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/main.cpp.s
.PHONY : main.cpp.s

qrc_res.o: qrc_res.cpp.o
.PHONY : qrc_res.o

# target to build an object file
qrc_res.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/qrc_res.cpp.o
.PHONY : qrc_res.cpp.o

qrc_res.i: qrc_res.cpp.i
.PHONY : qrc_res.i

# target to preprocess a source file
qrc_res.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/qrc_res.cpp.i
.PHONY : qrc_res.cpp.i

qrc_res.s: qrc_res.cpp.s
.PHONY : qrc_res.s

# target to generate assembly for a file
qrc_res.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CMEngine.dir/build.make CMakeFiles/CMEngine.dir/qrc_res.cpp.s
.PHONY : qrc_res.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CMEngine_autogen"
	@echo "... CMEngine_autogen_timestamp_deps"
	@echo "... CMEngine"
	@echo "... CMEngine_autogen/mocs_compilation.o"
	@echo "... CMEngine_autogen/mocs_compilation.i"
	@echo "... CMEngine_autogen/mocs_compilation.s"
	@echo "... Engine/GUI/guibuilder.o"
	@echo "... Engine/GUI/guibuilder.i"
	@echo "... Engine/GUI/guibuilder.s"
	@echo "... Engine/Panels/panel.o"
	@echo "... Engine/Panels/panel.i"
	@echo "... Engine/Panels/panel.s"
	@echo "... Engine/Panels/properties.o"
	@echo "... Engine/Panels/properties.i"
	@echo "... Engine/Panels/properties.s"
	@echo "... Engine/Rendering/renderer.o"
	@echo "... Engine/Rendering/renderer.i"
	@echo "... Engine/Rendering/renderer.s"
	@echo "... Engine/Windows/mainwindow.o"
	@echo "... Engine/Windows/mainwindow.i"
	@echo "... Engine/Windows/mainwindow.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qrc_res.o"
	@echo "... qrc_res.i"
	@echo "... qrc_res.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

